name = "Http2Proto"
uuid = "398584f8-2490-4402-97df-fb572a84d8e7"
authors = ["Gerasimos Panou <gerasimos.panou@gmail.com>"]
description = "HTTP/2 protocol stack"
version = "0.3.7"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Http2Frames = "7468a3b7-930e-48c8-a27b-9d42b62f3d3e"
Http2Hpack = "03a3583f-3b84-4ec3-931d-7334ff455684"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Base64 = "1.11.0"
BenchmarkTools = "1.6.0"
DataStructures = "0.18.22"
Dates = "1.11.0"
HTTP = "1.10.17"
Http2Frames = "0.4.4"
Http2Hpack = "0.2"
JSON3 = "1.14.3"
MbedTLS = "1.1.9"
ProfileView = "1.10.1"
Sockets = "1.11.0"
UUIDs = "1.11.0"
julia = "^1.11"

[source.Http2Frames]
url = "https://github.com/Grasimos/Http2Frames.jl"

[source.Http2Hpack]
url = "https://github.com/Grasimos/Http2Hpack.jl"
